@startuml
!theme plain

skinparam classAttributeIconSize 0
skinparam classFontStyle bold

class Student {
Name
}
Student "0..*" - "1..*" Course
(Student, Course) .. Enrollment
class Enrollment {
drop()
cancel()
}
@enduml