\i ../scripts/extensions/unaccent.sql
\i ../scripts/extensions/postgis.sql

-- types_interventions
\i ../scripts/interventions/type_intervention.sql
-- etats_tickets
\i ../scripts/signalements/statut.sql
-- urgences
\i ../scripts/signalements/urgence.sql
-- types_signalements
\i ../scripts/signalements/description.sql
-- etats_inventaires
\i ../scripts/mobilier/etat.sql
-- types_inventaires
\i ../scripts/mobilier/type.sql
-- materiaux
\i ../scripts/mobilier/materiau.sql
-- types_materiels
\i ../scripts/fournisseurs/type_materiel.sql
-- types_services
\i ../scripts/fournisseurs/types_services.sql
-- etats_fournisseurs
\i ../scripts/fournisseurs/etats_fournisseurs.sql
-- langues
\i ../scripts/fournisseurs/language.sql
-- etats_factures
\i ../scripts/factures/etat_facture.sql
-- techniciens
\i ../scripts/interventions/techniciens.sql
-- reporters
\i ../scripts/signalements/reporter.sql
-- fournisseurs
\i ../scripts/fournisseurs/fournisseurs.sql
-- fournisseurs_de_services
\i ../scripts/fournisseurs/fournisseurs_de_materiels.sql
-- fournisseurs_de_materiels
\i ../scripts/fournisseurs/fournisseurs_de_services.sql
-- factures
\i ../scripts/factures/factures.sql
-- inventaires
\i ../scripts/mobilier/inventaire.sql
-- tickets
\i ../scripts/interventions/tickets.sql
-- interventions
\i ../scripts/interventions/interventions.sql
-- interventions_factures
\i ../scripts/factures/intervention_facture.sql
-- signalements
\i ../scripts/signalements/signalements.sql


\i ../scripts/roles/roles.sql